### ISSUE TITLE
Various typos and spelling corrections

### ISSUE THREAD

**Issue by martinbudden** [ChipCE/SnakeOil-XY#15]
I've spotted a couple of typos/spelling mistakes

In https://github.com/ChipCE/SnakeOil-XY/blob/master/Doc/Manual/printing.md:
`Gillter or CF filled filaments might make the parts more brite.`
presumably you mean "Glitter" and "brittle"?

You use the word `tunning` a few times. Presumably you mean `tuning`?

**Comment by ChipCE** [comment]
Thank you!
